queue:
  name: Hosted VS2017

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npm run compile
  - task: RichCodeNavIndexer@0
    inputs:
      languages: typescript
      serviceConnection: 'rich-code-nav'
      githubServiceConnection: 'vsls-contrib'
